---
title: "Untitled"
author: "kj"
date: "6/3/2020"
output: html_document
---

```{r load libraries and files, echo=FALSE}
rm(list = ls())

library(tidyverse)
library(png)

if (file.exists(
  'C:/Users/kjones')){
  wdir <- "C:/Users/kjones/Documents/GitHub/neon-plant-sampling/vst_dendrometer"
}

year <- "2025"

df <-  readRDS(paste(wdir, year, "sourceData/vst_merged_data.rds", sep='/'))

## remove dead trees from WREF INC0050440
# dead <- c("NEON.PLA.D12.YELL.01988",
#           "NEON.PLA.D19.DEJU.00771",
#           "NEON.PLA.D12.YELL.01849",
#           "NEON.PLA.D19.BONA.00973",
#           "NEON.PLA.D13.NIWO.00891", 
#           "NEON.PLA.D19.BONA.00720",
#           "NEON.PLA.D12.YELL.01897",
#           "NEON.PLA.D16.WREF.04402",
#           "NEON.PLA.D16.WREF.04416", 
#           "NEON.PLA.D16.WREF.02213",
#           "NEON.PLA.D19.BONA.00720",
#           "NEON.PLA.D16.WREF.04437",
#           "NEON.PLA.D16.WREF.03461",
#           "NEON.PLA.D19.BONA.00443") 
# 
# df <- df[!df$individualid%in%dead,]

```


```{r load allometry lookups, echo=FALSE, message=FALSE, warning=FALSE}

## having trouble with relative paths

## pull from Sam's spreadsheet in neonplants repo


equations <- read.csv(paste(wdir, 'allometries/chojnacky_assignment.csv', sep='/'),
                      stringsAsFactors = F)

parameters <- read.csv(paste(wdir, 'allometries/chojnacky_parameters.csv', sep='/'),
                       stringsAsFactors = F)

```



```{r calculate biomass, echo=FALSE}


#ln(biomass_kg)= b0 + b1 * ln(diameter_cm)

eq <- select(equations, allometry_ID, taxonid=taxonID)
pm <- select(parameters, allometry_ID, b0, b1, minDiameter, maxDiameter)


#df <- left_join(df, eq)

df$agb <- NA

# # replace this with neonPlants? # #

for(i in 1:nrow(df)){
  ch_allID <- ifelse(is.na(df$taxonid[i])|df$taxonid[i]==''|!df$taxonid[i]%in%eq$taxonid, "H7", eq$allometry_ID[eq$taxonid==df$taxonid[i]])
  temp.b0 <- pm$b0[pm$allometry_ID==ch_allID]
  temp.b1 <- pm$b1[pm$allometry_ID==ch_allID]

  df$agb[i] <- round(exp(temp.b0 + temp.b1*log(df$stemdiameter[i])), digits=1)
}

## try mutate or apply
## make function first


```


```{r determine thresholds, echo=FALSE}

thresh <- df%>%
  group_by(siteid)%>%
  summarize(t2 = round(quantile(stemdiameter, 0.75), 1),
            t3 = round(quantile(stemdiameter, 0.95), 1),
            b2 = quantile(agb, 0.75),
            b3 = quantile(agb, 0.95),
            b2_d = min(stemdiameter[agb>=b2]),
            b3_d = min(stemdiameter[agb>=b3])
)


```


```{r comaparisonTable, echo=FALSE, message=FALSE, warning=FALSE}

dbh_agb_thresh <- thresh%>%
  select(siteid, "75th"=b2_d, "95th"=b3_d)#%>%

```


```{r write threshold file, echo=FALSE, message=FALSE, warning=FALSE}

write.csv(dbh_agb_thresh, paste(wdir, year, 'sourceData/dbh_abg_thresholds.csv', 
                                sep='/'), row.names=FALSE)

```


